### PR TITLE
fix: does not break with points that do not have coordinates

### LINKED ISSUE #14: Data with no lat/long breaks Mapeo web
[**Description**
](https://www.notion.so/digidem/Data-with-no-lat-long-breaks-Mapeo-web-47f2cb6a60da4108970aa9eabf1f81bb)Currently, it is possible to create data in Mapeo Mobile without any coordinates. When this data is synced with Mapeo Desktop Observations, and then included in an export to Webmap, it breaks the webmap interface by throwing an error `Uncaught TypeError: Invalid attempt to destructure non-iterable instance` (stacktrace pointing to [this line](https://github.com/digidem/mapeo-webmaps-public/blob/87736258dcfe3a31bca6c1fb5614f062f5f3c019/views/map.js#L278)). 

**This results in a number of errors:**

- Sometimes the satellite background layer (as set by the user) doesn't load
- Sometimes the title and description don't load
- Sometimes clicking the stories doesn't result in the map panning to that point
- The map doesn't zoom to the maximum extent of the points by default (fitBounds)
- The popups don't align with the points on the map
- Clicking the points doesn't do anything
- Sometimes the points don't show up on load

**To reproduce this behavior,**

1. Turn off the GPS on a device with Mapeo Mobile
2. Create a data point on that device's Mobile Mobile and bypass the "No GPS signal" warning screen by pressing Save.
3. Sync your data with Mapeo Desktop.
4. From Mapeo Desktop Observations, export a webmap.
5. Add this webmap on a [https://maps.mapeo.app](https://maps.mapeo.app) account.
6. See errors on the webmap public link.

**Suggested fix:**

Filter the data array on the front end to remove any data with no coordinates (or coordinates that are outside of an expected lat/long range). Or, only showing these data as cards in the sidebar, but omitting them from the map.

This is in lieu of what is likely to be a larger discussion on handling data without coordinates across Mapeo apps.

**Todo:**
Filter the data array on the front end to remove any data with no coordinates (or coordinates that are outside of an expected lat/long range)

### PR DESCRIPTION
**Pull request by ErikSin**
## Fix:
Previously, if there was a point with no coordinates two problems would occur:
1. Map would not zoom into the bounding box with all the points contained
2. User would not be able to click into these points.

This fix addresses this by filtering out these non-coordinate points when the bounding box is created, and disabling click events if the point does not have coordinates.

## Issue:
Closes #14 

Kapture 2022-01-04 at 16 33 10

### CODE REVIEW

File: views/map.js [hunk 1]
```diff
@@ -275,7 +277,10 @@ function featureCollection (features) {
 
 function getBounds (features = []) {
   const extent = [[-180, -85], [180, 85]]
-  for (const { geometry: { coordinates: [lon, lat] = [] } = {} } of features) {
+  //Filters all features without a coordinate
+  const filteredFeatures = features.filter(feat => (typeof feat.geometry.coordinates !== 'boolean' && feat.geometry.coordinates[0] !== null && feat.geometry.coordinates[1] !== null))
```
Comment (achou11) [inline views/map.js:281]: think it would be sufficient (and more resilient) to check that `geometry.coordinates` is an array of length 2 with non-null elements e.g. 

```js
Array.isArray(feat.geometry.coordinates) && 
feat.geometry.coordinates.length === 2 && // can probably omit this check if desired
feat.geometry.coordinates[0] !== null &&
feat.geometry.coordinates[1] !== null)
```

**Review by rudokemper — APPROVED** [review]
I have tested this branch out locally, and can confirm that Mapeo web map datasets with null coords are loading fine and no longer throwing an error, and that the click events are disabled for  those data points in the sidebar. I'd leave it to someone else from tech to do a code review, but in terms of the behavior, this is exactly what was needed, thanks @ErikSin!

File: views/map.js [hunk 2]
```diff
@@ -275,7 +277,10 @@ function featureCollection (features) {
...
+  console.log(filteredFeatures)
```
Comment (achou11) [inline views/map.js:282]: remove

File: models/map.js [hunk 3]
```diff
@@ -35,6 +35,12 @@ function MapModel () {
 
     emitter.on(events.ZOOM_TO, function (id) {
       const match = state.features.filter(f => id === f.properties._id)
+      console.log(match)
```
Comment (achou11) [inline models/map.js:38]: remove

File: models/map.js [hunk 4]
```diff
@@ -35,6 +35,12 @@ function MapModel () {
...
+      //If there are no-coordinates to zoom to, does nothing
+      if(!match[0] || (typeof match[0].geometry.coordinates === 'boolean' || match[0].geometry.coordinates[0]===null || match[0].geometry.coordinates[1]===null))
+      {
+        return
+      }
```
Comment (achou11) [inline models/map.js:43]: similar suggestion to https://github.com/digidem/mapeo-webmaps-public/pull/15/files#r778395069 i.e. checking that the `coordinates` field is an array of 2 non-null values

separately, can avoid emitting the event that triggers this in the first place by doing this check in the relevant view (`/views/list.js`). the click handler that emits the event is called [here](https://github.com/digidem/mapeo-webmaps-public/blob/87736258dcfe3a31bca6c1fb5614f062f5f3c019/views/list.js#L77-L80) so it would be a matter of moving this logic there and conditionally calling the handler. think keeping it here in the model is fine though

**Comment by achou11** [comment]
ideally would've used yarn since it was initially created using that but maybe worth converting the project to just use npm? could do as a follow-up but would require a couple of small changes to `package.json` and `deploy.yml`

File: views/list.js [hunk 5]
```diff
@@ -73,11 +73,17 @@ ListView.prototype.createElement = function (props) {
...
+            && match[0].geometry.coordinates[0] != undefined 
+            && match[0].geometry.coordinates[1] != undefined)
+         
           return html`
-          <button class='item' onclick=${props.onClick.bind(
+          <button class='item' onclick=${hasCoords ? props.onClick.bind(
             null,
             f.properties._id
-          )}>
+          ) :"return"}>
```
Comment (achou11) [inline views/list.js:86]: does `null` or `undefined` work here? can't remember the internals of nanohtml too well 😅

Comment (ErikSin) [reply views/list.js:86]: Actually I suppose it would make more sense to use `''` here, since its a templating language

Comment (ErikSin) [reply views/list.js:86]: wait, im confusing the html with the button binding property

Comment (ErikSin) [reply views/list.js:86]: No, I think it does make sense to use `return` because it is templating into `button onClick=return'. I can't find anything in the nanohtml documentation that says what to do in this case. But it seems to b working with return.

Comment (achou11) [reply views/list.js:86]: adding "return" as a string will leave it in the html which we don't want. if you provide a falsy value, nanohtml should omit that handler as a whole (similar to jsx)

**Comment by ErikSin** [comment]
> ideally would've used yarn since it was initially created using that but maybe worth converting the project to just use npm? could do as a follow-up but would require a couple of small changes to `package.json` and `deploy.yml`

good catch. What if we used both npm and yarn? I could update the package.json, and then just let the github actions use yarn

**Comment by achou11** [comment]
> > ideally would've used yarn since it was initially created using that but maybe worth converting the project to just use npm? could do as a follow-up but would require a couple of small changes to `package.json` and `deploy.yml`
> 
> good catch. What if we used both npm and yarn? I could update the package.json, and then just let the github actions use yarn

yeah i think it would be fine to do that for now. personally would move it away from yarn whenever we get the chance to but not an urgent todo

File: views/list.js (hunk 5 above)
Comment (ErikSin) [reply views/list.js:86]: Ok! sounds good
